# Generated by Django 4.1.5 on 2023-01-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=5000)),
                ('text_translation', models.CharField(max_length=5000)),
                ('message_date', models.DateTimeField(verbose_name='date published')),
                ('channel_name', models.CharField(max_length=100)),
                ('view_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
            ],
        ),
    ]
