# Generated by Django 4.1.5 on 2023-02-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_channels_message_message_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channels',
            new_name='Channel',
        ),
    ]
