# Generated by Django 4.1.5 on 2023-02-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_message_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply_count',
        ),
    ]
