# Generated by Django 4.1.5 on 2023-02-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_channel_channel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel_toggle',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
