# Generated by Django 4.1.5 on 2023-02-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_channel_category_channel_channel_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_group', models.CharField(max_length=100)),
            ],
        ),
    ]
