# Generated by Django 4.1.5 on 2023-02-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_toggle',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
