# Generated by Django 4.1.5 on 2023-02-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='share_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='view_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
