# Generated by Django 4.1.5 on 2023-02-05 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_filter_is_active_alter_filter_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='filter',
            name='share_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='filter',
            name='text_filter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='translation_filter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='view_count',
            field=models.IntegerField(blank=True),
        ),
    ]
