# Generated by Django 4.1.5 on 2023-02-05 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_filter_end_date_alter_filter_share_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='end_date',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
