# Generated by Django 4.1.5 on 2023-02-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_filter_share_count_alter_filter_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
