# Generated by Django 4.1.5 on 2023-02-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_filter_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_toggle',
            field=models.BooleanField(default=True),
        ),
    ]
