# Generated by Django 4.1.5 on 2023-02-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_channel_channel_toggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sort_by_date', models.CharField(max_length=100)),
                ('view_count', models.IntegerField()),
            ],
        ),
    ]
