# Generated by Django 4.1.5 on 2023-02-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_parameters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Parameter',
        ),
    ]
