# Generated by Django 4.1.5 on 2023-02-05 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_rename_parameters_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='view_count',
            new_name='message_load_number',
        ),
    ]
