# Generated by Django 4.1.5 on 2023-02-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_rename_view_count_parameter_message_load_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='message_sort_by_date',
            field=models.CharField(choices=[('UP', 'upward'), ('DOWN', 'downward')], max_length=10),
        ),
    ]
