# Generated by Django 4.1.5 on 2023-02-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_parameter_message_sort_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='message_retrieve_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('message_id', 'channel_name')},
        ),
    ]
