# Generated by Django 4.1.5 on 2023-02-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_parameter_message_retrieve_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='channel_group',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
