# Generated by Django 4.1.5 on 2023-02-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_group_channel_group_alter_parameter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='message_retrieve_number',
            new_name='message_retrieve_limit',
        ),
    ]
