# Generated by Django 4.1.5 on 2023-02-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_rename_message_retrieve_number_parameter_message_retrieve_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='api_hash',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='api_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
