# Generated by Django 4.1.5 on 2023-02-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_parameter_api_hash_parameter_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
