# Generated by Django 4.1.5 on 2023-02-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_filter_filter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='user_picture',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
