# Generated by Django 4.1.5 on 2023-02-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_channel_channel_id_channel_channel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.IntegerField(unique=True),
        ),
    ]
