# Generated by Django 4.1.5 on 2023-02-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_channel_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='filter_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='text_filter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='translation_filter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
