# Generated by Django 4.1.5 on 2023-02-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_filter_filter_name_alter_filter_text_filter_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_translation',
            field=models.CharField(max_length=10000),
        ),
    ]
