# Generated by Django 4.1.5 on 2023-02-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alter_message_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='user_phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
