# Generated by Django 4.1.5 on 2023-03-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_parameter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='message_load_number',
        ),
    ]
